//Notes:
//If want to comment out a key, put "//" or "#" near to the key as starter, no space between them, right comment like this "//linear_or_follow=1"
//If delete a line, then the key's value in that line will be not be set to fw, even a default value, except linear_or_follow, Tchannels, Troom_os
//mac is in hex like 18:4E:34:23:05:96
//If any value is invalid format, then it will not be set to fw.
//capcode and power offset in decimal
//en_tcal, Tchannels, Tchannels_os, Tchannels_os_low, Troom_os, linear_or_follow in decimal
//pwr_table_11b, pwr_table_11g, pwr_table_11n_ht20, pwr_table_11n_ht40, pwr_table_11ax_he20, pwr_table_11ax_he40 in decimal
//pwr_mode=FB   //BF  or  BO  or  FO，O is NONE, PLACE HOLDER
//capcode=20, valid in normal fw. In mfg mode, not used, mp_set_xtal_cap does it.
//xtal=36

//ALL LINES ABOVE SHOULD BE REMOVED WHEN USED

rf_para={
	xtal_mode=FM
	capcode=32

	power_offset=1,0,0,0,0,0,-3,0,0,0,0,0,13,0

	en_tcal=0
	//linear_or_follow=1						//optional
	//Tchannels=2412,2427,2442,2457,2472		//optional
	Tchannel_os=180,168,163,160,157
	Tchannel_os_low=199,186,170,165,160
	//Troom_os=256								//optional

	pwr_mode=FB
	
	pwr_oft_bz=5,3,3,3,3
	
	pwr_table_11b=22,22,22,18
	pwr_table_11g=21,20,20,20,20,20,18,16
	pwr_table_11n_ht20=20,20,20,20,20,19,17,15
	pwr_table_11n_ht40=19,19,19,19,19,18,16,14
	pwr_table_11ax_he20=20,20,20,20,20,19,17,17,15,14
	pwr_table_11ax_he40=19,19,19,19,19,18,16,16,14,13
	
	pwr_table_ble=8
}

