//Notes:
//If want to comment out a key, put "//" or "#" near to the key as starter, no space between them, right comment like this "//linear_or_follow=1"
//If delete a line, then the key's value in that line will be not be set to fw, even a default value, except linear_or_follow, Tchannels, Troom_os
//If any value is invalid format, then it will not be set to fw.
//capcode and power offset in decimal
//
// power offset should configure the channel 1/7/13  
//
//en_tcal, Tchannels, Tchannels_os, Tchannels_os_low, Troom_os, linear_or_follow in decimal
//pwr_table_11b, pwr_table_11g, pwr_table_11n_ht20, pwr_table_11n_ht40, pwr_table_11ax_he20, pwr_table_11ax_he40 in decimal
//ALL LINES ABOVE SHOULD BE REMOVED

rf_para={
	capcode=32

	power_offset=1,0,0,0,0,0,-3,0,0,0,0,0,13,0

	en_tcal=0
	Tchannel_os=180,168,163,160,157
	Tchannel_os_low=199,186,170,165,160

	pwr_oft_bz=5,3,3,3,3
}

